### ISSUE TITLE
Winter Psion at end of mission weirdness

### ISSUE THREAD

**Issue by NamesAreHard6600** [Tatuzudo/Vextra#42]
- the winter psion behaves weirdly if he's alive at the end of the fight : its ability will trigger at the same time as enemies are leaving. If a vek is supposed to be frozen, it will freeze during it's leaving animation and then unfreeze. It looks weird and it's unclear whether this counts for the achievement (it does not), but it's not very important

**Comment by Tatuzudo** [comment]
This one was the best solution I found. The alternative was enemies being frozen while they leave, so I just added an animation of ice breaking on top of them. I can remove freezing on the last turn entirely if it seems better.

**Comment by Tatuzudo** [comment]
Last turn freezes are also counting for the achievement now

**Comment by NamesAreHard6600** [comment]
I'm assuming we're not fixing this, because there's no better solution? If so, we should mark it as wontfix.

**Comment by Tatuzudo** [comment]
Yes, I'll close it
