### ISSUE TITLE
Reactive Psion move before affect

### ISSUE THREAD

**Issue by NamesAreHard6600** [Tatuzudo/Vextra#43]
- when the psion that makes enemies push adjacent tiles on death (reactive psion?) is active, its ability takes a lot of time to trigger and you can actually act before it activates, so it's possible to move a mech _before_ a previously killed enemy "explodes" and change the outcome of the kill this way

**Comment by Tatuzudo** [comment]
Maybe I can add a delay after the explosion to make the board busy?
I'll try this later
