### ISSUE TITLE
Subjective: Ice Crawler

### ISSUE THREAD

**Issue by NamesAreHard6600** [Tatuzudo/Vextra#55]
tosx wrote:

> The Ice Crawler Leader's weapon description is so long that it also makes me think it could stand some streamlining; it takes the already busy crawler weapon and adds freeze explosion and a second direction to it. Does it need variable damage? Does it need to be 2 directions? Does it need to stop at buildings/mountains? Would set damage in one direction that didn't stop at buildings/mountains still be interesting? The freeze-explosion is already adding a lot of overhead vs the non-boss ice crawler, why not simplify. (Related, do the other ice crawlers need variable damage?)

**Comment by Tatuzudo** [comment]
I would be ok with fixed damage for all ice crawlers
1 for beta and 2 for alpha and boss?
maybe 3 for boss and we make it shoot in only one direction?

**Comment by NamesAreHard6600** [comment]
Yeah, I think the variable damage was only in there cause we were like "lasers"! at first and then thought it would be cool to do it reverse, so I'm cool to get rid of it. As well as the extra direction, but stick with 2 damage probably because it already freezes, and I think 3 damage would be more beneficial to the player.

**Comment by Tatuzudo** [comment]
Ok, sounds good to me. If we do this we should probably change the icecrawler achievement too because it will be very hard to do. We could change it to any icecrawler instead of just the boss, or only 2 enemies instead of 3. I think the 1st option is better.

**Comment by NamesAreHard6600** [comment]
Pushed these changes.
