### ISSUE TITLE
Balancing Changes From Unfair Players

### ISSUE THREAD

**Issue by NamesAreHard6600** [Tatuzudo/Vextra#56]
1. Nurse is OP in Unfair. Changes that could be made: Make if not heal fire and acid from Vek, like Viscera Nanobots and not like repair and/or make it a static one healing instead of damage based. 
2. Antlions being stable in core is causing first island issues: Possible Solutions: Move it to Unique or remove stable
3. Termites are too weak. I think the best solution is to swap termites and antlion. 
4. Corrosive is too weak, especially in comparison to others. No clue how to fix that. But it seemed that it was more beneficial to be able to acid vek then harmful, and was worth keeping alive to also fill a Vek slot, since the acid rarely even harmed any mech anyway: it was just going to die.

**Comment by Tatuzudo** [comment]
Nurse now can be damaged by friendly fire.
I changed antlion from 3 to 2 hp, possibly enought to keep it a core enemy.
Not listed here, but I increased the thunderbug hp and speed by 1.

**Comment by NamesAreHard6600** [comment]
I have additionally swapped termites and antlion. This means, 1, 2, and 3 are all (hypothetically) dealt with, although more testing will of course be needed. I have left the antlion health change, but if it is too weak, we can give its health back, or consider swapping it back.

**Comment by Tatuzudo** [comment]
I hope 4 is ok as well with the acid psion change
